pull_request_rules:
  - name: automatic merge when CI passes and 1 reviews
    conditions:
      - status-success=ci
      - "#approved-reviews-by>=1"
      - label=auto merge
      - label!=work in progress
    actions:
      merge:
        method: merge
